### ISSUE TITLE
Adding an inventory does not create cluster variables files

### ISSUE THREAD

**Issue by ivanfetch** [FairwindsOps/pentagon#145]
Creating an additional inventory with `pentagon add inventory -f ../config.yml ....` does not generate the `clusters` sub-directory and `vars.yml` files, required to create a cluster later with E.G. `pentagon add kops.cluster -f vars.yml`.

I believe adding an inventory should create the same clusters that were created during the initial `start-project` command, at least if the `config.yml` file is passed to `pentagon add inventory`. Even if one of the working or production clusters is not needed in a new inventory, the content of the `clusters` sub-directory can be adjusted before `pentagon add kops.cluster` is run.

**Comment by ejether** [comment]
I disagree a little bit that a new inventory should contain a `production` and `staging` cluster but I do agree that a reference `vars.yml` would be very useful. 

In fact, instead of `production` and `staging`  clusters at all, I'm thinking that we should only produce a reference `vars.yml` by default since it seems like the frequency with which we actually use `staging` and `production` in new projects is waning. 

What are your thoughts on that?

**Comment by ivanfetch** [comment]
I agree, a reference variables file could facilitate the creation of working, prod, or maybe clusters of any other name.  Would the reference variables file contain values for working and production clusters, as specified by `start-project` options? E.G. cluster name, DNS zone, etc.
