### ISSUE TITLE
ssh_config does not respect initialization IP ranges

### ISSUE THREAD

**Issue by philipcristiano** [FairwindsOps/pentagon#33]
The `lib/pentagon/config/local/ssh_config.jinja` has hardcoded IP addresses and does not respect the values set when running Pentagon.

**Comment by ejether** [comment]
Are you referring to the ipspace created by the `--vpc-cidr-base`, `--working-kubernetes-network-cidr`, `--production-kubernetes-network-cidr` ?

**Comment by philipcristiano** [comment]
The config is specific to host IPs so the `--working-kubernetes-network-cidr` `--production-kubernetes-network-cidr` are the appropriate options that should trigger config. 

https://github.com/reactiveops/pentagon/blob/6628a9195d0caf0fd812fbbe2418592777650c62/lib/pentagon/config/local/ssh_config.jinja#L2

**Comment by opennomad** [comment]
Those hardcoded values are my doing. I'm happy to take a stab at it, but since the ssh config doesn't accept ranges or CIDRs it gets to be more tricky. All you can do are wild cards. So dependending on how things slice up some `ipcalc` magic might be needed. Some more details here https://serverfault.com/questions/803902/how-can-i-match-a-cidr-range-for-an-ssh-config-host-entry

**Comment by opennomad** [comment]
Perhaps something like this will work: http://codegist.net/snippet/python/output_speshak_python, which doesn't seems to actually do the right thing.

**Comment by ejether** [comment]
Thats a neat idea!  Thanks for taking this on @opennomad
